Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (modelforge 0.12.1 (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages), Requirement.parse('modelforge<0.14.0,>=0.13.4'), {'lookout-sdk-ml'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/analyzer", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'modelforge<0.14.0,>=0.13.4' distribution was not found and is required by lookout-sdk-ml
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (modelforge 0.14.0 (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages), Requirement.parse('modelforge<0.14.0,>=0.13.4'), {'lookout-sdk-ml'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/analyzer", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'modelforge<0.14.0,>=0.13.4' distribution was not found and is required by lookout-sdk-ml
INFO:package:Preparing /tmp/pkg
INFO:package:Importing lookout.style.typos
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/analyzer", line 11, in <module>
    load_entry_point('lookout-sdk-ml', 'console_scripts', 'analyzer')()
  File "/Users/irina/lookout-sdk-ml/lookout/__main__.py", line 18, in main
    return handler(args)
  File "/Users/irina/lookout-sdk-ml/lookout/core/package.py", line 27, in package_cmdline_entry
    args.repo, args.user, args.token)
  File "/Users/irina/lookout-sdk-ml/lookout/core/package.py", line 55, in package
    package_name = _process_analyzers(analyzers, wd, log)
  File "/Users/irina/lookout-sdk-ml/lookout/core/package.py", line 98, in _process_analyzers
    cls = importlib.import_module(a).analyzer_class
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/irina/style-analyzer/lookout/style/typos/__init__.py", line 2, in <module>
    from lookout.style.typos.analyzer import IdTyposAnalyzer
  File "/Users/irina/style-analyzer/lookout/style/typos/analyzer.py", line 23, in <module>
    from lookout.style.format.utils import generate_comment
  File "/Users/irina/style-analyzer/lookout/style/format/__init__.py", line 4, in <module>
    from lookout.style.format.analyzer import FormatAnalyzer
  File "/Users/irina/style-analyzer/lookout/style/format/analyzer.py", line 20, in <module>
    from lookout.core.metrics import submit_event
ImportError: cannot import name 'submit_event' from 'lookout.core.metrics' (/Users/irina/lookout-sdk-ml/lookout/core/metrics.py)
INFO:package:Preparing /tmp/pkg
INFO:package:Importing lookout.style.typos
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/analyzer", line 11, in <module>
    load_entry_point('lookout-sdk-ml', 'console_scripts', 'analyzer')()
  File "/Users/irina/lookout-sdk-ml/lookout/__main__.py", line 18, in main
    return handler(args)
  File "/Users/irina/lookout-sdk-ml/lookout/core/package.py", line 27, in package_cmdline_entry
    args.repo, args.user, args.token)
  File "/Users/irina/lookout-sdk-ml/lookout/core/package.py", line 55, in package
    package_name = _process_analyzers(analyzers, wd, log)
  File "/Users/irina/lookout-sdk-ml/lookout/core/package.py", line 98, in _process_analyzers
    cls = importlib.import_module(a).analyzer_class
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/irina/style-analyzer/lookout/style/typos/__init__.py", line 2, in <module>
    from lookout.style.typos.analyzer import IdTyposAnalyzer
  File "/Users/irina/style-analyzer/lookout/style/typos/analyzer.py", line 23, in <module>
    from lookout.style.format.utils import generate_comment
  File "/Users/irina/style-analyzer/lookout/style/format/__init__.py", line 4, in <module>
    from lookout.style.format.analyzer import FormatAnalyzer
  File "/Users/irina/style-analyzer/lookout/style/format/analyzer.py", line 20, in <module>
    from lookout.core.metrics import submit_event
ImportError: cannot import name 'submit_event' from 'lookout.core.metrics' (/Users/irina/lookout-sdk-ml/lookout/core/metrics.py)
